### ISSUE TITLE
Metody Numeryczne, Zad G, test 19

### ISSUE THREAD

**Issue by webdevmrpl** [BaCa2-project/BaCa2#35]
Problem z testem 19 nie został rozwiązany. Na zwykłej wersji programu ten test jest akceptowany, natomiast na wersji 2 mam następujące dane z logów checkera:
Checking differences:

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=0.0000000000e+00   abs=0.0000000000e+00

rel=6.2930003323e-09   abs=6.2930003430e-09

rel=2.0163834187e-08   abs=2.0163834269e-08

rel=3.2925004784e-09   abs=3.2925004945e-09

rel=1.3600751850e-08   abs=1.3600752080e-08

rel=8.1846018530e-10   abs=8.1846018851e-10

rel=8.1485099357e-09   abs=8.1485099779e-09

rel=1.7092552238e-08   abs=1.7092552373e-08

rel=3.8746145743e-09   abs=3.8746146291e-09

rel=1.0744982048e-08   abs=1.0744982237e-08

rel=1.1199412948e-08   abs=1.1199413397e-08

rel=7.1301367275e-09   abs=7.1301369253e-09

rel=1.7783854336e-08   abs=1.7783855277e-08

rel=3.8332477714e-09   abs=3.8332479413e-09

rel=1.3505960231e-08   abs=1.3505961016e-08

rel=2.9317078517e-08   abs=2.9317080763e-08

rel=7.2337029587e-09   abs=7.2337034140e-09

rel=4.2524829407e-09   abs=4.2524832544e-09

rel=1.5297406833e-08   abs=1.5297408007e-08

rel=5.7937725155e-09   abs=5.7937730169e-09

rel=8.8982196670e-09   abs=8.8982206048e-09

rel=9.0208324062e-09   abs=9.0208334136e-09

rel=9.0046041207e-09   abs=9.0046050616e-09

rel=6.7643568934e-09   abs=6.7643577406e-09

rel=1.3624289527e-08   abs=1.3624291473e-08

rel=1.6416467094e-08   abs=1.6416469517e-08

rel=4.4218030756e-09   abs=4.4218038120e-09

rel=1.4321203094e-08   abs=1.4321205555e-08

rel=6.8464536713e-09   abs=6.8464549585e-09

rel=1.5794367579e-08   abs=1.5794370700e-08

rel=1.3091389641e-09   abs=1.3091392415e-09

rel=1.0154900244e-08   abs=1.0154902474e-08

rel=1.1351974850e-08   abs=1.1351977580e-08

rel=4.3035934774e-09   abs=4.3035945918e-09

rel=2.4194871853e-08   abs=2.4194878545e-08

rel=7.5739197050e-09   abs=7.5739219341e-09

rel=2.4506229674e-09   abs=2.4506237040e-09

rel=2.3967212973e-08   abs=2.3967220653e-08

rel=1.6630979242e-08   abs=1.6630985034e-08

rel=3.2256030800e-10   abs=3.2256042282e-10

rel=1.0414950693e-08   abs=1.0414954676e-08

rel=3.8949060857e-08   abs=3.8949076409e-08

rel=6.1405377448e-09   abs=6.1405402985e-09

rel=1.6263485160e-08   abs=1.6263492331e-08

rel=4.1193221061e-09   abs=4.1193239930e-09

rel=7.4019964787e-09   abs=7.4019999019e-09

rel=2.5833667233e-08   abs=2.5833679862e-08

rel=2.7820373138e-08   abs=2.7820387993e-08

rel=6.9641100055e-10   abs=6.9641137301e-10

rel=2.6800607881e-08   abs=2.6800622832e-08

rel=4.3400122346e-09   abs=4.3400147920e-09

rel=4.9788174200e-09   abs=4.9788204670e-09

rel=2.7930526080e-08   abs=2.7930543878e-08

rel=2.3467881349e-08   abs=2.3467897181e-08

rel=1.8869386519e-08   abs=1.8869399376e-08

rel=9.0467386911e-09   abs=9.0467451308e-09

rel=2.4393519628e-08   abs=2.4393537412e-08

rel=1.2010562500e-08   abs=1.2010571870e-08

rel=1.1578269803e-08   abs=1.1578279002e-08

rel=2.2701623695e-08   abs=2.2701642566e-08

rel=2.3095743715e-09   abs=2.3095763080e-09

rel=1.2958018997e-08   abs=1.2958030204e-08

rel=9.3425345262e-09   abs=9.3425429615e-09

rel=1.4553706679e-08   abs=1.4553720229e-08

rel=1.0888981359e-08   abs=1.0888991708e-08

rel=5.1381266539e-09   abs=5.1381316979e-09

rel=1.4367630545e-08   abs=1.4367645296e-08

rel=8.8694060381e-09   abs=8.8694154243e-09

rel=6.5452348474e-09   abs=6.5452419040e-09

rel=3.6535091862e-09   abs=3.6535132697e-09

rel=3.2851649370e-08   abs=3.2851688037e-08

rel=1.3524325513e-08   abs=1.3524341425e-08

rel=1.8010978482e-08   a

**Comment by ZyndramZM** [comment]
@webdevmrpl Spodziewałem się tego błędu - wynika to z faktu, że wynik wzorcowy obliczany w architekturze amd64 różni się od wyniku w architekturze x86-32. Było to już niemożliwe do zmiany w czasie trwania kursu, bo wymagałoby albo odrzucania jednych rozwiązań (takich, które są napisane, aby przechodziły przy sprawdzaniu 32-bitowym i nie przejdą przy sprawdzaniu 64-bitowym), albo drugich (sprawdzarka nie obsługuje kompilacji 32-bitowej).

Ze względu na powyższe zdecydowaliśmy się _obniżyć_ dokładność sprawdzania dla tego testu, tak aby akceptował oba rozwiązania. Niestety skutkuje to rozbieżnością w wynikach sprawdzania, jednak możliwe one będą do naprawienia dopiero w kolejnych latach, kiedy pozbędziemy się już konieczności bycia zbieżnym ze starą bacą.
